version: '3.9'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    restart: always

  app:
    build: .
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
